name: Build, Lint, Test
on: [push]

jobs:
  build:
    name: Build, lint, and test Core on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Check for Change Files
        run: node common/scripts/install-run-rush.js change -v

      - name: Install Dependencies
        run: node common/scripts/install-run-rush.js install --bypass-policy

      - name: Lint Core
        run: |
          cd packages/core
          yarn lint

      - name: Lint Editor
        run: |
          cd packages/editor
          yarn lint

      - name: Lint Player
        run: |
          cd packages/player
          yarn lint

      - name: Test Core
        run: |
          cd packages/core
          yarn test --ci --coverage --maxWorkers=2

      - name: Test Editor
        run: |
          cd packages/editor
          yarn test --ci --coverage --maxWorkers=2

      - name: Test Player
        run: |
          cd packages/player
          yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: node common/scripts/install-run-rush.js rebuild --verbose --timeline
