name: PR Change File Checker
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Check for Change Files
        run: node common/scripts/install-run-rush.js change -v
